### PR TITLE
Add a github workflow

### PR DESCRIPTION
**Pull request by RealKC**
I'll keep this as a draft until CI passes

Based on kcshot's workflow: https://github.com/RealKC/kcshot/blob/master/.github/workflows/ci.yml

### CODE REVIEW

**Comment by RealKC** [comment]
Looks like it passes (and is fast!) https://github.com/RealKC/starboard/actions/runs/3169790726

**Comment by lucastarche** [comment]
Looks good! Also one point to clippy for already complaining hahaha

Only one question, is it ran on every commit? Or only on a PR? (Just curiosity, don't really know how CI works in GH :x)

**Comment by RealKC** [comment]
> is it ran on every commit? Or only on a PR? (Just curiosity, don't really know how CI works in GH :x)

It's ran on every push to master, and every push to a PR

**Comment by lucastarche** [comment]
That's cool, thanks for the PR! :D

**Pull request merged**
